from . import account_invoice
from . import account_invoice_line
from . import account_invoice_tax
from . import account_tax
from . import avalara_onthefly
from . import avalara_salestax
from . import avalara_salestax_address_validate
from . import exemption_code
from . import product_category
from . import product_tax_code
from . import product_template
from . import res_partner
from . import sale_order
from . import sale_order_line
from . import shipping_order_line
from . import shipping_rate_config
